products = {
    "products": [
      {
        "name": "REI Co-op Trailmade 2 Tent with Footprint",
        "image_link": "https://www.rei.com/media/9f0bbecd-8ed5-46f9-97ac-50f3f33b671c.jpg",
        "product_url": "https://www.rei.com/product/216300/rei-co-op-trailmade-2-tent-with-footprint",
        "price": "$299.00",
        "description": "The REI Co-op Trailmade 2 Tent is designed for two campers, featuring a durable footprint and easy setup. It offers excellent ventilation and weather protection, making it perfect for weekend getaways.",
        "capacity": 2,
        "weight": "5 lbs 8 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "7 x 20 inches",
        "material": "Ripstop polyester with aluminum poles",
        "special_features": ["Included footprint", "Multiple doors", "Weather-resistant"],
        "id": "1"
      },
      {
        "name": "Big Agnes Copper Spur HV UL2 Tent",
        "image_link": "https://www.rei.com/media/6341cfd5-14e1-48a7-8e8f-b25925ba6ec5.jpg",
        "product_url": "https://www.rei.com/product/164193/big-agnes-copper-spur-hv-ul2-tent",
        "price": "$499.95",
        "description": "The Big Agnes Copper Spur HV UL2 Tent is a lightweight, two-person tent that combines durability with livability. Its high-volume design maximizes interior space, making it ideal for backpacking.",
        "capacity": 2,
        "weight": "3 lbs 2 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "6 x 19 inches",
        "material": "Ripstop nylon with DAC Featherlite poles",
        "special_features": ["Ultralight", "Double doors", "High-volume design"],
        "id": "2"
      },
      {
        "name": "NEMO Dagger OSMO 2P Tent",
        "image_link": "https://www.rei.com/media/2aa89f32-7e9e-4a72-90dc-39760202bdc3.jpg",
        "product_url": "https://www.rei.com/product/200550/nemo-dagger-osmo-2p-tent",
        "price": "$499.95",
        "description": "The NEMO Dagger OSMO 2P Tent is a versatile and spacious tent for two, featuring a unique design that enhances ventilation and stability. It includes a footprint for added protection.",
        "capacity": 2,
        "weight": "3 lbs 14 oz",
        "season_rating": "3-season",
        "setup_type": "Semi-freestanding",
        "packed_size": "6.5 x 19.5 inches",
        "material": "OSMO ripstop nylon with DAC poles",
        "special_features": ["OSMO waterproofing", "Included footprint", "Enhanced ventilation"],
        "id": "3"
      },
      {
        "name": "Mountain Hardwear Mineral King 2 Tent with Footprint",
        "image_link": "https://www.rei.com/media/7d518251-e621-46ff-b506-f05b28133ff4.jpg",
        "product_url": "https://www.rei.com/product/164699/mountain-hardwear-mineral-king-2-tent-with-footprint",
        "price": "$399.00",
        "description": "The Mountain Hardwear Mineral King 2 Tent is built for durability and comfort, featuring a spacious interior and a footprint for extra protection. Perfect for weekend camping trips.",
        "capacity": 2,
        "weight": "6 lbs 1 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "7.5 x 23 inches",
        "material": "Solution-dyed polyester with aluminum poles",
        "special_features": ["Included footprint", "Color-coded setup", "Extra headroom"],
        "id": "4"
      },
      {
        "name": "Marmot Superalloy 3-Person Tent",
        "image_link": "https://www.rei.com/media/93764116-2a2b-430e-8284-6748e504896c.jpg",
        "product_url": "https://www.rei.com/product/245879/marmot-superalloy-3-person-tent",
        "price": "$599.00",
        "description": "The Marmot Superalloy 3-Person Tent is ultra-lightweight and designed for three campers. It features a unique pole structure for maximum space and stability in windy conditions.",
        "capacity": 3,
        "weight": "4 lbs 6 oz",
        "season_rating": "3-season",
        "setup_type": "Semi-freestanding",
        "packed_size": "7 x 21 inches",
        "material": "Ripstop nylon with DAC Featherlite NFL poles",
        "special_features": ["Ultralight design", "Wind-stable structure", "Maximum interior space"],
        "id": "5"
      },
      {
        "name": "Big Agnes Tiger Wall UL2 Solution-Dyed Tent",
        "image_link": "https://www.rei.com/media/34a5a77e-c5e3-4fc9-bc8f-4903ea2425e8.jpg",
        "product_url": "https://www.rei.com/product/188354/big-agnes-tiger-wall-ul2-solution-dyed-tent",
        "price": "$449.95",
        "description": "The Big Agnes Tiger Wall UL3 Solution-Dyed Tent is a lightweight, three-person tent that offers ample space and comfort. Its solution-dyed fabric provides UV protection and reduces environmental impact.",
        "capacity": 3,
        "weight": "2 lbs 15 oz",
        "season_rating": "3-season",
        "setup_type": "Semi-freestanding",
        "packed_size": "6 x 19 inches",
        "material": "Solution-dyed ripstop nylon with DAC poles",
        "special_features": ["Ultralight", "Solution-dyed fabric", "Three-person capacity"],
        "id": "6"
      },
      {
        "name": "ALPS Mountaineering Chaos 2 Tent",
        "image_link": "https://www.rei.com/media/484c7b5f-8669-4c48-abcd-14c06ca596a8.jpg",
        "product_url": "https://www.rei.com/product/193080/alps-mountaineering-chaos-2-tent",
        "price": "$199.99",
        "description": "The ALPS Mountaineering Chaos 2 Tent is a budget-friendly option for two campers. It features a simple design and is easy to set up, making it great for beginners.",
        "capacity": 2,
        "weight": "5 lbs 14 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "7 x 22 inches",
        "material": "Polyester taffeta with fiberglass poles",
        "special_features": ["Budget-friendly", "Easy setup", "Beginner-friendly"],
        "id": "7"
      },
      {
        "name": "NEMO Aurora 2 Backpacking Tent with Footprint",
        "image_link": "https://www.rei.com/media/f24f5222-796d-48fb-8474-106b6ad86c3f.jpg",
        "product_url": "https://www.rei.com/product/246448/nemo-aurora-2-backpacking-tent-with-footprint",
        "price": "$399.95",
        "description": "The NEMO Aurora 2 Backpacking Tent is designed for two campers, featuring a spacious interior and a footprint for added protection. Perfect for weekend adventures.",
        "capacity": 2,
        "weight": "4 lbs 9 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "7 x 21 inches",
        "material": "Ripstop nylon with aluminum poles",
        "special_features": ["Included footprint", "Large doors", "Generous headroom"],
        "id": "8"
      },
      {
        "name": "Big Agnes C Bar 3 Tent",
        "image_link": "https://www.rei.com/media/7f883ea1-5fbf-48b1-a49d-8dcafe2382b9.jpg",
        "product_url": "https://www.rei.com/product/232434/big-agnes-c-bar-3-tent",
        "price": "$449.95",
        "description": "The Big Agnes C Bar 3 Tent is a spacious option for three campers, featuring a durable design and excellent ventilation. Ideal for family camping trips.",
        "capacity": 3,
        "weight": "5 lbs 13 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "7 x 22 inches",
        "material": "Polyester ripstop with DAC pressfit poles",
        "special_features": ["Family-sized", "Multiple doors", "Good ventilation"],
        "id": "9"
      },
      {
        "name": "NEMO Hornet OSMO Ultralight 2P Tent",
        "image_link": "https://www.rei.com/media/6e6c380c-4119-40c9-919a-2db6bba3d507.jpg",
        "product_url": "https://www.rei.com/product/238835/nemo-hornet-osmo-ultralight-2p-tent",
        "price": "$499.95",
        "description": "The NEMO Hornet OSMO Ultralight 2P Tent is designed for ultralight backpacking, offering a compact and lightweight solution for two campers without sacrificing comfort.",
        "capacity": 2,
        "weight": "2 lbs 6 oz",
        "season_rating": "3-season",
        "setup_type": "Semi-freestanding",
        "packed_size": "5.5 x 18 inches",
        "material": "OSMO ripstop nylon with DAC Featherlite poles",
        "special_features": ["Ultralight", "OSMO waterproofing", "Minimal weight"],
        "id": "10"
      },
      {
        "name": "REI Co-op Trail Hut 2 Tent with Footprint",
        "image_link": "https://www.rei.com/media/56b03fff-1b1b-4bba-bb46-63429f9576d6.jpg",
        "product_url": "https://www.rei.com/product/164366/rei-co-op-trail-hut-2-tent-with-footprint",
        "price": "$299.00",
        "description": "The REI Co-op Trail Hut 2 Tent is a spacious and durable option for two campers, featuring a footprint for added protection and easy setup for your outdoor adventures.",
        "capacity": 2,
        "weight": "5 lbs 15 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "7 x 20 inches",
        "material": "Ripstop polyester with aluminum poles",
        "special_features": ["Included footprint", "Multiple doors", "Spacious interior"],
        "id": "11"
      },
      {
        "name": "Big Agnes Blacktail Hotel 2 Tent",
        "image_link": "https://www.rei.com/media/5f37563a-acc4-4393-82ee-2ef943c41941.jpg",
        "product_url": "https://www.rei.com/product/244881/big-agnes-blacktail-hotel-2-tent",
        "price": "$349.95",
        "description": "The Big Agnes Blacktail Hotel 2 Tent is designed for comfort and convenience, featuring a spacious interior and easy setup. Perfect for family camping trips.",
        "capacity": 2,
        "weight": "5 lbs 6 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "7 x 21 inches",
        "material": "Polyester ripstop with DAC pressfit poles",
        "special_features": ["Extended vestibule", "Hotel-style space", "Easy setup"],
        "id": "12"
      },
      {
        "name": "Big Agnes Sheep Mountain 1 Tent",
        "image_link": "https://www.rei.com/media/a9927da6-c1ea-4620-a44d-c1cde752d4ab.jpg",
        "product_url": "https://www.rei.com/product/244895/big-agnes-sheep-mountain-1-tent",
        "price": "$249.95",
        "description": "The Big Agnes Sheep Mountain 1 Tent is a lightweight option for solo campers, featuring a compact design and easy setup for your outdoor adventures.",
        "capacity": 1,
        "weight": "3 lbs 8 oz",
        "season_rating": "3-season",
        "setup_type": "Freestanding",
        "packed_size": "6 x 18 inches",
        "material": "Polyester ripstop with aluminum poles",
        "special_features": ["Compact design", "Single door", "Good ventilation"],
        "id": "13"
      },
    {
            "name": "Big Agnes Tiger Wall UL2 Solution-Dyed Tent",
            "image_link": "https://www.rei.com/media/product/example.jpg",
            "product_url": "https://www.rei.com/product/example",
            "price": "$399.95", 
            "description": "The Big Agnes Tiger Wall UL2 is a lightweight, two-person tent that offers a balance of weight and livability. Its solution-dyed fabric reduces environmental impact while providing excellent UV resistance.",
            "capacity": 2,
            "weight": "2 lbs 8 oz",
            "season_rating": "3-season",
            "setup_type": "Semi-freestanding",
            "packed_size": "5.5 x 18 inches",
            "material": "Solution-dyed ripstop nylon with DAC poles",
            "special_features": ["Ultralight", "Solution-dyed fabric", "UV resistant"],
            "id": "14"
        },
        {
            "name": "REI Co-op Half Dome 2 Tent with Footprint",
            "image_link": "https://www.rei.com/media/09ae9844-d7cf-4450-8a5c-d49b58e3ac23.jpg",
            "product_url": "https://www.rei.com/product/243702/rei-co-op-half-dome-2-tent-with-footprint",
            "price": "$249.00",
            "description": "The REI Co-op Half Dome 2 Tent is a reliable choice for two campers, featuring a spacious interior and a footprint for added durability. It's easy to set up and perfect for weekend adventures.",
            "capacity": 2,
            "weight": "5 lbs 5 oz",
            "season_rating": "3-season",
            "setup_type": "Freestanding",
            "packed_size": "7 x 21 inches",
            "material": "Ripstop nylon with aluminum poles",
            "special_features": ["Included footprint", "Color-coded setup", "Multiple pockets"],
            "id": "15"
        },
        {
            "name": "Big Agnes Tiger Wall UL1 Solution-Dyed Tent",
            "image_link": "https://www.rei.com/media/c77720fe-aee6-4724-a8a1-890847ef23fd.jpg",
            "product_url": "https://www.rei.com/product/188351/big-agnes-tiger-wall-ul1-solution-dyed-tent",
            "price": "$399.95",
            "description": "The Big Agnes Tiger Wall UL1 is a lightweight, one-person tent designed for solo backpackers. Its solution-dyed fabric offers UV protection and reduces environmental impact.",
            "capacity": 1,
            "weight": "2 lbs 2 oz",
            "season_rating": "3-season",
            "setup_type": "Semi-freestanding",
            "packed_size": "5.5 x 17.5 inches",
            "material": "Solution-dyed ripstop nylon with DAC poles",
            "special_features": ["Ultralight", "Solution-dyed fabric", "Single door"],
            "id": "16"
        },
        {
            "name": "REI Co-op Trailmade 1 Tent with Footprint",
            "image_link": "https://www.rei.com/media/f9024f40-8053-42ea-a941-e217c3bd5246.jpg",
            "product_url": "https://www.rei.com/product/243610/rei-co-op-trailmade-1-tent-with-footprint",
            "price": "$249.00",
            "description": "The REI Co-op Trailmade 1 Tent is perfect for solo campers, featuring a durable footprint and easy setup. It provides excellent weather protection for your outdoor adventures.",
            "capacity": 1,
            "weight": "4 lbs 8 oz",
            "season_rating": "3-season",
            "setup_type": "Freestanding",
            "packed_size": "6 x 18 inches",
            "material": "Ripstop polyester with aluminum poles",
            "special_features": ["Included footprint", "Weather resistant", "Easy setup"],
            "id": "17"
        },
        {
            "name": "NEMO Dragonfly OSMO 1P Tent",
            "image_link": "https://www.rei.com/media/00debb47-abff-44f5-9003-3e4a92561b60.jpg",
            "product_url": "https://www.rei.com/product/215774/nemo-dragonfly-osmo-1p-tent",
            "price": "$399.95",
            "description": "The NEMO Dragonfly OSMO 1P Tent is a lightweight and spacious option for solo campers. It features a unique design for enhanced ventilation and stability.",
            "capacity": 1,
            "weight": "2 lbs 13 oz",
            "season_rating": "3-season",
            "setup_type": "Semi-freestanding",
            "packed_size": "6 x 19 inches",
            "material": "OSMO ripstop nylon with DAC Featherlite poles",
            "special_features": ["OSMO waterproofing", "Enhanced ventilation", "Ultralight"],
            "id": "18"
        },
        {
            "name": "Mountain Hardwear Aspect 3 Tent",
            "image_link": "https://www.rei.com/media/f5fa66f8-31ad-4a81-a9ff-59f0e669e17c.jpg",
            "product_url": "https://www.rei.com/product/242550/mountain-hardwear-aspect-3-tent",
            "price": "$499.00",
            "description": "The Mountain Hardwear Aspect 3 Tent is designed for three campers, offering a spacious interior and excellent weather protection. Ideal for family camping trips.",
            "capacity": 3,
            "weight": "6 lbs 8 oz",
            "season_rating": "3-season",
            "setup_type": "Freestanding",
            "packed_size": "8 x 24 inches",
            "material": "Solution-dyed polyester with DAC poles",
            "special_features": ["Multiple doors", "Large vestibules", "Family-sized"],
            "id": "19"
        },
        {
            "name": "Big Agnes C Bar 2 Tent",
            "image_link": "https://www.rei.com/media/c10ba31b-fdb5-434d-8191-e2fc0297df50.jpg",
            "product_url": "https://www.rei.com/product/244888/big-agnes-c-bar-2-tent",
            "price": "$349.95",
            "description": "The Big Agnes C Bar 2 Tent is a versatile and durable option for two campers. It features a simple setup and excellent ventilation for comfortable camping.",
            "capacity": 2,
            "weight": "4 lbs 7 oz",
            "season_rating": "3-season",
            "setup_type": "Freestanding",
            "packed_size": "6.5 x 20 inches",
            "material": "Polyester ripstop with DAC pressfit poles",
            "special_features": ["Easy setup", "Good ventilation", "Durable design"],
            "id": "20"
        },
        {
            "name": "Big Agnes Tiger Wall UL3 Solution-Dyed Tent",
            "image_link": "https://www.rei.com/media/ca1e42a0-fc71-4164-8573-e55b1527f032.jpg",
            "product_url": "https://www.rei.com/product/188358/big-agnes-tiger-wall-ul3-solution-dyed-tent",
            "price": "$499.95",
            "description": "The Big Agnes Tiger Wall UL3 Solution-Dyed Tent is a lightweight, three-person tent that offers ample space and comfort. Its solution-dyed fabric provides UV protection and reduces environmental impact.",
            "capacity": 3,
            "weight": "2 lbs 15 oz",
            "season_rating": "3-season",
            "setup_type": "Semi-freestanding",
            "packed_size": "6 x 19 inches",
            "material": "Solution-dyed ripstop nylon with DAC poles",
            "special_features": ["Ultralight", "Solution-dyed fabric", "Three-person capacity"],
            "id": "21"
        }
    ]
}